---
baseURL: "https://www.fountaincitykc.org/"
title: "Fountain City Church"
publishDir: "../fountaincitykc.github.io"
paginate: 10
disableKinds: ["RSS","taxonomy","term"]
params:
  datetimeFormat: "Jan 2, 2006 @ 3:04pm"
...
